# Generated by Django 4.2.5 on 2023-09-29 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticuloDeportivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("deporte", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                ("valor", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Univalluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Estudiante", "Estudiante"),
                            ("Funcionario", "Funcionario"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tipo_documento", models.CharField(max_length=50)),
                ("numero_documento", models.CharField(max_length=50, unique=True)),
                ("codigo_estudiante", models.CharField(max_length=50, null=True)),
                ("correo", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_prestamo", models.DateTimeField(auto_now_add=True)),
                ("fecha_vencimiento", models.DateTimeField()),
                (
                    "articulo_deportivo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="univalle_app.articulodeportivo",
                    ),
                ),
                (
                    "univalluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="univalle_app.univalluno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Multa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_multa", models.PositiveIntegerField()),
                ("pagada", models.BooleanField(default=False)),
                ("fecha_pago", models.DateTimeField(blank=True, null=True)),
                (
                    "prestamo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="univalle_app.prestamo",
                    ),
                ),
            ],
        ),
    ]
