# Generated by Django 4.2.5 on 2023-09-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("univalle_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulodeportivo",
            name="prestado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="univalluno",
            name="numero_documento",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="univalluno",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("CC", "Cédula de Ciudadanía"),
                    ("TI", "Tarjeta de Identidad"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="univalluno", unique_together={("tipo_documento", "numero_documento")},
        ),
    ]
