# Generated by Django 4.2.5 on 2023-09-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("univalle_app", "0002_articulodeportivo_prestado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="multa",
            name="fecha_generada",
            field=models.DateField(null=True),
        ),
    ]
