# Generated by Django 4.2.5 on 2023-09-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("univalle_app", "0003_multa_fecha_generada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulodeportivo",
            name="valor",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
